name: Accessible Accordion
author: mashalla
category: Widgets
tags: [accordion, element, window, style]
#docs: http://ascribedata.com/moo/dialog/
demo: http://www.accessiblemootoolsdemo.iao.fraunhofer.de/Mootools_Widgets/index.html
current: 1.0

sources:
  - "Source/accordion.js"
  - "Source/demo.js"